### ISSUE TITLE
when is _hasCache updating?

### ISSUE THREAD

**Issue by GeonhanLee** [CarterGames/MultiScene#1]
When does `_hasCache` in `EditorSceneHelper` update to false?
I couldn't find any reference about it, and I think `EditorSceneHelper` functions are not working correctly because its not updating.

e.g `buildSettingsOptions = EditorSceneHelper.ScenesInBuildSettings.ToDisplayOptions()` on `SceneGroupEditor.OnEnable()`
buildSettingsOptions  is not updating properly when new scene is added on buildsettings.

**Comment by JonathanMCarter** [comment]
Hi, 

Good catch here, I totally didn't notice this when I made that system, may bad. I'll take a look at this and get a fix up ASAP

**Comment by JonathanMCarter** [comment]
Just committed a hotfix to the repository which should rectify this issue, the only edited files are:
- EditorSceneHelper.cs
- SceneGroupEditor.cs
